# Generated by Django 3.2.17 on 2023-02-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230206_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите фотографию блюда', upload_to='recipes/images/', verbose_name='Фото блюда'),
        ),
    ]
