# Generated by Django 3.2.17 on 2023-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Загрузите фотографию блюда', upload_to='recipes_images/', verbose_name='Фото блюда'),
        ),
    ]
